name: 👀 Report a bug
description: Reporting bugs helps improve the app!
title: "[Bug]: "

body:
  - type: textarea
    attributes:
      label: Bug description
      description: The more details we have, the faster we can find the bug!
      placeholder: My Proxmox connection isn't working; I get an infinite loading screen when I try to connect.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the bug?
      placeholder: |
        1. Open the app
        2. Add a server
        3. Seeing the connection error even though everything is fine
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: What should ProxmoxBar do?
      placeholder: The connection to my Proxmox server should work and there should be no infinite loading.
    validations:
      required: true

  - type: input
    attributes:
      label: Device
      description: On which device did you encounter this bug?
      placeholder: MacBook Pro M2
    validations:
      required: true

  - type: input
    attributes:
      label: macOS Version
      description: On which macOS version did you encounter this bug?
      placeholder: macOS 15
    validations:
      required: true

  - type: input
    attributes:
      label: ProxmoxBar Version
      description: ProxmoxBar -> Settings -> Version displayed at the bottom of the page
      placeholder: "1.0.7"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots / Video
      description: This will help us resolve the bug faster
      placeholder: Click on the 📎 icon to import a photo/video
    validations:
      required: false